name: Trigger auto deployment for deep-research-mcp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/deep-research-mcp-AutoDeployTrigger-1aa52aea-f5df-4bd4-b6ba-52b1236f40af.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEEPRESEARCHMCP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEEPRESEARCHMCP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEEPRESEARCHMCP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: hzgenaicontainerregistry.azurecr.io
          registryUsername: ${{ secrets.DEEPRESEARCHMCP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEEPRESEARCHMCP_REGISTRY_PASSWORD }}
          containerAppName: deep-research-mcp
          resourceGroup: AIWebinarRAG01_RG
          imageToBuild: hzgenaicontainerregistry.azurecr.io/deep-research-mcp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


